### ISSUE TITLE
This is not an issue, but more of questions

### ISSUE THREAD

**Issue by smboy** [mistercrunch/Airflow#130]
Hi, I've  been following Airflow and the project seems to be very interesting. I've a local copy of the Airflow running on my mac and the UI is really awesome.. I've pointed airflow to my local mysql db for metadata. Few questions:

1. There seems to be some issues with the code display on UI.
2. From the UI, Browse -> Task Instance -> create. It would be good on adding some kind of greyed out description for the fields. I'm kind of lost on adding values to fields such as: Duration, state and JobId. what values should I give? Inspite of giving the values, it throws the following error: Failed to create record. __init__() takes at least 3 arguments (1 given)
3. Are there any upcoming features or plans for creating DAGs and Tasks from the UI instead of code?
4. Have you experimented with jobs scheduled on AWS using Airflow?

Thanks a lot for putting this tool. I'm in the process of replacing some of the crontab/Aws datapipeline flow that i'm running. I'm currently experimenting (running poc) on Chronos (with mesos) and Airflow.

thanks!

**Comment by mistercrunch** [comment]
Hi, Thanks for the feedback!
1. Which browser are you using? I've been using chrome and not caring about browser compatibility yet, but I will take the time to look at it.
2. Oh. I think this is fixed in the current head of master, I need to push a fresher version to pypi. Everything in the browse menu should be read only. I'm leveraging the CRUD that ships with Flask Admin to make these entities searchable / filterable / browsable. I had forgotten to flip the `readonly` switch for Task Instance. The only way to alter or make new task instance is by running or clearing tasks, which can only be defined in code.
3. Creating DAG from the UI would be sweet, but it's important to me that DAGs are code, as opposed to metadata in a database. Having DAGs define as code opens a lot of possibility, and the rigor and processes around source control / code review. So when feature makes it, the output of the form would be Python code, probably in the form of a PR.
4. Yes! I work at Airbnb and we're in early production stages doing just that. The master and worker nodes run on AWS and talk to Hive / S3 / MySQL all on AWS. We also tend to develop from boxes on that side of the fence too, meaning we're not running Airflow on our laptops but through ssh on AWS boxes.

Where did you hear about Airflow!?  We haven't really been communicated about it just yet as it's still in beta. We're doing a big push internally at the moment and externally in the next few months.

**Comment by smboy** [comment]
Sorry I'm asking you this question, but Is there any reason why you are creating one more data flow scheduler when you already have chronos? The reason I ask this question is, I can drop one of it and concentrate on another for my implementation.

For the AWS - S3/Hive, if you already have operators built, can you share with me? It would help me immensely instead of re-writing existing ones.

**Comment by mistercrunch** [comment]
Our growing need around scheduling complex DAGs would require growing Chronos far beyond what it was first intended to do. 

Chronos is great as a scalable company crontab, but the level of complexity towards which we're headed needs something more extensible, dynamic, time/DAG aware and with better data viz and client tools to perform complex surgeries on the DAGs.

**Comment by smboy** [comment]
Thanks a lot for the details. It makes sense given the limited functionality of Chronos. In the past I worked on Azkaban, Appworx (UC4) and Autosys. I tried looking into oozie, but it is really complex. Having a light weight solution is good for many use cases. 

Few questions:
- How do you handle security? say given Airflow is launched on one of the ec2 instance and its workers run on EMR instances. The UI is fairly open and be accessed. How do you restrict to certain a audience? I think Chronos also lacks this functionality and I'm pretty there is a easy work around on this.
- For the AWS - S3/Hive, if you already have operators built, can you share with me? It would help me immensely instead of re-writing existing ones.

Thanks again. Let me know if there is any plan for airflow which is worth sharing. I will be happy to contribute to this project in some form.

**Comment by mistercrunch** [comment]
We should chat, send me an email (maximebeauchemin@gmail.com), I'll give you my phone number.

All the operators that we have are in the repo and well documented here:
http://airflow.readthedocs.org/en/latest/code.html#operators

I think there should be a S3Sensor landing soon. 

You can always use the BashOperator or PythonOperator to do pretty much anything, and deriving BaseOperator to create your own operator is very straightforward.

**Comment by mistercrunch** [comment]
Oh, and about authentication, there's a little bit of information here:
http://pythonhosted.org/airflow/installation.html#web-authentication

Closing this item for now, please open another one if you have more questions!
