### ISSUE TITLE
Problems running backfill example in tutorial

### ISSUE THREAD

**Issue by cgelman** [mistercrunch/Airflow#194]
I've been trying pretty hard to get the basic backfill working with your example tutorial.  

The issue I'm getting is that after the first task finishes (print_date) the task stays in the "started" state and all the other tasks keep waiting.   

I'm using all the default out-of-the-box settings - so a Sequential Executor with the sqlite db.
I'm running on an amazon linux ami instance and installed with no problems via installing in a  virtualenv environment.

Having stepped through the code a bit - I can confirm that the task successfully executes, and base_executor.change_state() get's called with SUCCESS status.

But after that, the flow never seems to load that status from anywhere.  It tries to load it from the db via the refresh_from_db() function(), but that function is never finding it, and my db seems to in fact be empty.  

Any help would be much appreciated... ;)

**Comment by mistercrunch** [comment]
Did you run off of the pipy version? Let me try a fresh install and see if I can hit the same problem. I was planning on pushing a fresher version to pypi soon, I'll do it sooner if that fixes this problem.

**Comment by cgelman** [comment]
Yes, I did use the pipy version.  I also tried a full install of the latest codebase and that didn't seem to help.

**Comment by mistercrunch** [comment]
I just did some tests and had hit the same issue. Since there's been a lot of improvements since the version that was in pypi I decided to push the latest version to pypi (0.5.0), upgrade and test from there. It worked well.

So you'll want to `pip install airflow --upgrade`, and then you should be able to run the backfill, just be careful that the start date of the backfill matches the start_date of your DAG/tasks, it's something I need to clarify and line up in the docs.

Another minor thing I had to do was to force refresh the website in my browser since older css/js was cached and the website looked off. On a MAC it's [command+shift+r].

**Comment by mistercrunch** [comment]
I also updated the docs to set `depends_on_past=False` and aligned the start_date in the backfill with the `start_date`

**Comment by cgelman** [comment]
Thanks!  Doing the upgrade, plus setting depends_on_past=False and aligning my start_dates with the target dates I was doing fixed the issue for me.  Much appreciated!
