### ISSUE TITLE
Tasks are not persisted into database

### ISSUE THREAD

**Issue by shenghuy** [mistercrunch/Airflow#205]
Hi Maxime,

First of all, thanks much for this amazing project. We here at Lyft started to test on airflow, and the initial results are pretty solid.

One thing I noticed though is in the database [we use postgres], there is no records for table 'task', while in the command line, when I run 'airflow list_tasks <dag_id>', I can get all the tasks. 
------------------------------------
airflow=> select * from task;
┌────────┬─────────┬───────┬───────────┬────────────┬──────────┬─────────────────┐
│ dag_id │ task_id │ owner │ task_type │ start_date │ end_date │ depends_on_past │
├────────┼─────────┼───────┼───────────┼────────────┼──────────┼─────────────────┤
└────────┴─────────┴───────┴───────────┴────────────┴──────────┴─────────────────┘
(0 rows)

-------------------------------------------
$ airflow list_tasks test_saurabh
x
y
z

------------------------------------------
So my wild guess is that: all the tasks [DAG nodes] & their dependency relations are stored in RAM only, they won't be written to database, am I right?

Best,
Shenghu

**Comment by mistercrunch** [comment]
BaseOperator is a sqlalchemy model, and all tasks could in theory be synced to the database fairly easily. Early on I stopped syncing tasks to the database because it was confusing around the source of truth and keeping things in sync. 

My current approach to what should be stored in the database is only stateful information that cannot be rebuilt from the code itself, like timestamps, statuses and such. The DB is complementary to the metadata in the code, not a representation of it. The task_instance table is heavily used and very central, and in newer version there's information persisted around the DAG model as well. 

One of the challenge around keeping all that in sync with the database is that we want to be able to alter the code in source control and have multiple repository and branches that can be slightly different. It bring the question of what's driving what's in the database (some master or produciton node) and other nodes (dev / personal repo / branches) have to operate without relying on the DB....

Tasks are kind of stateless, as task instances store their states over time.

**Comment by shenghuy** [comment]
Thanks for your explanation. I am good for not store task into db.
