### ISSUE TITLE
Sensor operators clogging the pipeline

### ISSUE THREAD

**Issue by hominot** [mistercrunch/airflow#236]
I have been working on a project using a local executor.
As the pipeline grew, the number of HivePartitionSensor grew to an extent where there are more than the parallelism value of the local executor. Consequently, all the "real" operators never get a chance to run.

What do you think is the best practice/solution around this problem?

**Comment by mistercrunch** [comment]
If you are planning on running Airflow in production, I'd recommend using the CeleryExecutor and setting up a certain number of workers to make sure you have enough slots.

In the meantime, if you want to get more mileage out of the LocalExecutor, you have the option to crank up the parallelism on it in your `airflow.cfg`. It's the `[core] -> parallelism` setting. Depending on the resource consumption of your tasks and how big your box is, you can crank that up to much higher level than the default 16 (128?!). The only danger with that is that if some of your task take a significant amount of resources and append to all run simultaneously, it can bring that box in a bad state, so you have to account for that.

For instance the HiveOperator can be memory hungry because it's a wrapper around the Hive CLI and 128 of those running at the same time is a stretch even for a very beefy box.

As of v0.7, we have a new "Airflow pools" feature to limit concurrency to limit parallelism on any set of tasks. You could then set up a HiveOperator pool (in the UI), and assign your HiveOperator tasks to that pool (as you instantiate tasks).
